-- Seed departments, default money accounts and expense categories A-Z.
-- Run after 042_finance_core.sql
--
-- Idempotent: rows are inserted only when missing, so admin edits
-- (renames, deactivations, classification changes) are never overwritten.

insert into public.fin_departments (id, name, sort_order) values
  ('accommodation', 'Accommodation', 10),
  ('restaurant', 'Restaurant', 20),
  ('kitchen', 'Kitchen', 30),
  ('housekeeping', 'Housekeeping & Laundry', 40),
  ('facilities', 'Property & Facilities', 50),
  ('construction', 'Construction & Development', 60),
  ('marketing', 'Marketing & Sales', 70),
  ('administration', 'Administration', 80),
  ('technology', 'Technology', 90),
  ('human_resources', 'Human Resources', 100),
  ('security', 'Safety & Security', 110),
  ('events', 'Events & Activities', 120),
  ('finance', 'Finance', 130),
  ('shared', 'Shared / General', 140)
on conflict (id) do nothing;

-- Booking payment methods (src/utils/bookings.ts PaymentMethod) map to these
-- accounts for cash-position reporting. Opening balances start at 0; admins
-- enter real figures in Expenses -> Settings -> Accounts.
insert into public.fin_accounts (id, name, account_type, default_methods, sort_order) values
  ('acc-cash', 'Cash drawer', 'cash', array['cash'], 10),
  ('acc-bank', 'Bank account', 'bank', array['bank-transfer', 'card'], 20),
  ('acc-bkash', 'bKash wallet', 'mobile_wallet', array['bkash'], 30),
  ('acc-nagad', 'Nagad wallet', 'mobile_wallet', array['nagad'], 40),
  ('acc-rocket', 'Rocket wallet', 'mobile_wallet', array['rocket'], 50)
on conflict (id) do nothing;

-- Top-level categories: (code, name, classification, department, requires_approval, threshold, requires_description)
with parents (code, name, classification, department_id, requires_approval, approval_threshold, requires_description, sort_order) as (
  values
    ('A', 'Property Rent and Occupancy', 'operating_expense', 'facilities', false, null::numeric, false, 1),
    ('B', 'Construction, Renovation and Development', 'capital_asset', 'construction', true, 50000::numeric, false, 2),
    ('C', 'Furniture, Fixtures and Equipment', 'capital_asset', 'accommodation', true, 50000::numeric, false, 3),
    ('D', 'Room and Accommodation Supplies', 'operating_expense', 'accommodation', false, null, false, 4),
    ('E', 'Restaurant and Kitchen Purchases', 'inventory', 'restaurant', false, null, false, 5),
    ('F', 'Kitchen Equipment and Appliances', 'capital_asset', 'kitchen', true, 50000::numeric, false, 6),
    ('G', 'Utilities and Connectivity', 'operating_expense', 'shared', false, null, false, 7),
    ('H', 'Salaries, Wages and Human Resources', 'operating_expense', 'human_resources', false, null, false, 8),
    ('I', 'Housekeeping and Laundry', 'operating_expense', 'housekeeping', false, null, false, 9),
    ('J', 'Repairs and Maintenance', 'operating_expense', 'facilities', false, null, false, 10),
    ('K', 'Transportation and Logistics', 'operating_expense', 'shared', false, null, false, 11),
    ('L', 'Marketing, Advertising and Sales', 'operating_expense', 'marketing', false, null, false, 12),
    ('M', 'Technology and Software', 'operating_expense', 'technology', false, null, false, 13),
    ('N', 'Administration and Office Supplies', 'operating_expense', 'administration', false, null, false, 14),
    ('O', 'Professional and Legal Services', 'operating_expense', 'administration', false, null, false, 15),
    ('P', 'Licensing, Government Fees and Compliance', 'operating_expense', 'administration', false, null, false, 16),
    ('Q', 'Customer Experience and Hospitality', 'operating_expense', 'accommodation', false, null, false, 17),
    ('R', 'Safety and Security', 'operating_expense', 'security', false, null, false, 18),
    ('S', 'Events and Additional Services', 'operating_expense', 'events', false, null, false, 19),
    ('T', 'Financial Costs', 'financing_cost', 'finance', false, null, false, 20),
    ('U', 'Insurance', 'operating_expense', 'finance', false, null, false, 21),
    ('V', 'Assets and Capital Expenditure', 'capital_asset', 'shared', true, 50000::numeric, false, 22),
    ('W', 'Inventory and Procurement', 'inventory', 'shared', false, null, false, 23),
    ('X', 'Refundable Deposits and Advances', 'deposit_advance', 'finance', true, null, false, 24),
    ('Y', 'Pre-opening and Setup Costs', 'operating_expense', 'shared', false, null, false, 25),
    ('Z', 'Other and Uncategorized', 'other', 'shared', false, null, true, 26)
)
insert into public.fin_categories (
  id, parent_id, code, name, classification, department_id,
  requires_approval, approval_threshold, requires_description, sort_order
)
select
  'cat-' || lower(code), null, code, name, classification, department_id,
  requires_approval, approval_threshold, requires_description, sort_order
from parents
on conflict (id) do nothing;

-- Subcategories: (parent code, name, classification override or null = inherit)
with subs (code, name, classification, sort_order) as (
  values
    -- A. Property Rent and Occupancy
    ('A', 'Monthly property rent', null, 1),
    ('A', 'Advance rent', 'deposit_advance', 2),
    ('A', 'Security deposit', 'deposit_advance', 3),
    ('A', 'Lease-related payments', null, 4),
    ('A', 'Property management fees', null, 5),
    ('A', 'Property-related service charges', null, 6),
    ('A', 'Other occupancy costs', null, 7),
    -- B. Construction, Renovation and Development
    ('B', 'Initial construction', null, 1),
    ('B', 'Ongoing construction', null, 2),
    ('B', 'Building materials', null, 3),
    ('B', 'Cement, sand, bricks, and aggregates', null, 4),
    ('B', 'Wood and timber', null, 5),
    ('B', 'Steel and metalwork', null, 6),
    ('B', 'Roofing', null, 7),
    ('B', 'Flooring and tiles', null, 8),
    ('B', 'Painting', null, 9),
    ('B', 'Plumbing installation', null, 10),
    ('B', 'Electrical installation', null, 11),
    ('B', 'Carpentry', null, 12),
    ('B', 'Masonry', null, 13),
    ('B', 'Interior design', null, 14),
    ('B', 'Architectural services', null, 15),
    ('B', 'Engineering and consultancy', null, 16),
    ('B', 'Contractor payments', null, 17),
    ('B', 'Labour costs', null, 18),
    ('B', 'Site transportation', null, 19),
    ('B', 'Renovation', null, 20),
    ('B', 'Structural repairs', 'operating_expense', 21),
    ('B', 'Expansion projects', null, 22),
    ('B', 'Other development costs', null, 23),
    -- C. Furniture, Fixtures and Equipment
    ('C', 'Beds', null, 1),
    ('C', 'Mattresses', null, 2),
    ('C', 'Pillows and bedding', 'operating_expense', 3),
    ('C', 'Wardrobes', null, 4),
    ('C', 'Tables and chairs', null, 5),
    ('C', 'Sofas', null, 6),
    ('C', 'Curtains and blinds', 'operating_expense', 7),
    ('C', 'Lighting fixtures', null, 8),
    ('C', 'Decorative items', 'operating_expense', 9),
    ('C', 'Mirrors', null, 10),
    ('C', 'Storage furniture', null, 11),
    ('C', 'Outdoor furniture', null, 12),
    ('C', 'Office furniture', null, 13),
    ('C', 'Kitchen furniture', null, 14),
    ('C', 'Other fixtures and furnishings', null, 15),
    -- D. Room and Accommodation Supplies
    ('D', 'Bedsheets', null, 1),
    ('D', 'Towels', null, 2),
    ('D', 'Blankets', null, 3),
    ('D', 'Pillows', null, 4),
    ('D', 'Toiletries', null, 5),
    ('D', 'Soap and shampoo', null, 6),
    ('D', 'Tissue paper', null, 7),
    ('D', 'Drinking water', null, 8),
    ('D', 'Room amenities', null, 9),
    ('D', 'Guest welcome supplies', null, 10),
    ('D', 'Laundry supplies', null, 11),
    ('D', 'Cleaning supplies', null, 12),
    ('D', 'Room replacement items', null, 13),
    ('D', 'Other accommodation consumables', null, 14),
    -- E. Restaurant and Kitchen Purchases
    ('E', 'Rice', null, 1),
    ('E', 'Vegetables', null, 2),
    ('E', 'Fruits', null, 3),
    ('E', 'Fish', null, 4),
    ('E', 'Meat', null, 5),
    ('E', 'Poultry', null, 6),
    ('E', 'Eggs', null, 7),
    ('E', 'Dairy products', null, 8),
    ('E', 'Cooking oil', null, 9),
    ('E', 'Spices', null, 10),
    ('E', 'Flour', null, 11),
    ('E', 'Dry goods', null, 12),
    ('E', 'Packaged food', null, 13),
    ('E', 'Bottled water', null, 14),
    ('E', 'Soft drinks', null, 15),
    ('E', 'Coffee and tea', null, 16),
    ('E', 'Other beverages', null, 17),
    ('E', 'Cooking gas', 'operating_expense', 18),
    ('E', 'Charcoal or other cooking fuel', 'operating_expense', 19),
    ('E', 'Kitchen consumables', null, 20),
    ('E', 'Food packaging', null, 21),
    ('E', 'Takeaway containers', null, 22),
    ('E', 'Disposable cutlery', null, 23),
    ('E', 'Other food and beverage purchases', null, 24),
    -- F. Kitchen Equipment and Appliances (durable vs low-value consumables)
    ('F', 'Refrigerators', null, 1),
    ('F', 'Freezers', null, 2),
    ('F', 'Ovens', null, 3),
    ('F', 'Stoves', null, 4),
    ('F', 'Burners', null, 5),
    ('F', 'Rice cookers', null, 6),
    ('F', 'Blenders', null, 7),
    ('F', 'Mixers', null, 8),
    ('F', 'Water filters', null, 9),
    ('F', 'Kitchen utensils', 'operating_expense', 10),
    ('F', 'Cooking pots', 'operating_expense', 11),
    ('F', 'Pans', 'operating_expense', 12),
    ('F', 'Knives', 'operating_expense', 13),
    ('F', 'Plates', 'operating_expense', 14),
    ('F', 'Bowls', 'operating_expense', 15),
    ('F', 'Glasses', 'operating_expense', 16),
    ('F', 'Cups', 'operating_expense', 17),
    ('F', 'Cutlery', 'operating_expense', 18),
    ('F', 'Serving equipment', 'operating_expense', 19),
    ('F', 'Other kitchen appliances', null, 20),
    -- G. Utilities and Connectivity
    ('G', 'Electricity', null, 1),
    ('G', 'Water', null, 2),
    ('G', 'Internet', null, 3),
    ('G', 'Telephone', null, 4),
    ('G', 'Gas', null, 5),
    ('G', 'Generator fuel', null, 6),
    ('G', 'Generator servicing', null, 7),
    ('G', 'Waste disposal', null, 8),
    ('G', 'Other utility services', null, 9),
    -- H. Salaries, Wages and Human Resources
    ('H', 'Staff salaries', null, 1),
    ('H', 'Daily wages', null, 2),
    ('H', 'Temporary labour', null, 3),
    ('H', 'Overtime', null, 4),
    ('H', 'Staff allowances', null, 5),
    ('H', 'Staff meals', null, 6),
    ('H', 'Staff accommodation', null, 7),
    ('H', 'Recruitment', null, 8),
    ('H', 'Training', null, 9),
    ('H', 'Uniforms', null, 10),
    ('H', 'Staff welfare', null, 11),
    ('H', 'Employee reimbursements', null, 12),
    ('H', 'Other personnel costs', null, 13),
    -- I. Housekeeping and Laundry
    ('I', 'Cleaning products', null, 1),
    ('I', 'Laundry detergent', null, 2),
    ('I', 'Disinfectants', null, 3),
    ('I', 'Mops and brushes', null, 4),
    ('I', 'Cleaning equipment', null, 5),
    ('I', 'Laundry services', null, 6),
    ('I', 'Laundry equipment', 'capital_asset', 7),
    ('I', 'Waste management', null, 8),
    ('I', 'Pest control', null, 9),
    ('I', 'Housekeeping supplies', null, 10),
    ('I', 'Other housekeeping costs', null, 11),
    -- J. Repairs and Maintenance
    ('J', 'Plumbing repairs', null, 1),
    ('J', 'Electrical repairs', null, 2),
    ('J', 'Furniture repairs', null, 3),
    ('J', 'Appliance repairs', null, 4),
    ('J', 'Air conditioning servicing', null, 5),
    ('J', 'Generator maintenance', null, 6),
    ('J', 'Water pump maintenance', null, 7),
    ('J', 'Painting and touch-ups', null, 8),
    ('J', 'Roof repairs', null, 9),
    ('J', 'Door and window repairs', null, 10),
    ('J', 'Equipment servicing', null, 11),
    ('J', 'Emergency repairs', null, 12),
    ('J', 'Other maintenance', null, 13),
    -- K. Transportation and Logistics
    ('K', 'Fuel', null, 1),
    ('K', 'Vehicle rental', null, 2),
    ('K', 'Vehicle maintenance', null, 3),
    ('K', 'Staff transportation', null, 4),
    ('K', 'Supplier collection', null, 5),
    ('K', 'Delivery charges', null, 6),
    ('K', 'Freight', null, 7),
    ('K', 'Courier services', null, 8),
    ('K', 'Travel for purchasing', null, 9),
    ('K', 'Travel for operations', null, 10),
    ('K', 'Parking and tolls', null, 11),
    ('K', 'Other logistics costs', null, 12),
    -- L. Marketing, Advertising and Sales
    ('L', 'Facebook advertising', null, 1),
    ('L', 'Social media promotion', null, 2),
    ('L', 'Photography', null, 3),
    ('L', 'Videography', null, 4),
    ('L', 'Graphic design', null, 5),
    ('L', 'Printing', null, 6),
    ('L', 'Brochures', null, 7),
    ('L', 'Signboards', null, 8),
    ('L', 'Outdoor advertising', null, 9),
    ('L', 'Website development', null, 10),
    ('L', 'Domain registration', null, 11),
    ('L', 'Hosting', null, 12),
    ('L', 'Digital tools and subscriptions', null, 13),
    ('L', 'Promotional materials', null, 14),
    ('L', 'Customer acquisition', null, 15),
    ('L', 'Influencer collaborations', null, 16),
    ('L', 'Events and promotional activities', null, 17),
    ('L', 'Other marketing costs', null, 18),
    -- M. Technology and Software
    ('M', 'Software subscriptions', null, 1),
    ('M', 'Website services', null, 2),
    ('M', 'Domain renewals', null, 3),
    ('M', 'Hosting', null, 4),
    ('M', 'Computer purchases', 'capital_asset', 5),
    ('M', 'Mobile devices', 'capital_asset', 6),
    ('M', 'Printers', 'capital_asset', 7),
    ('M', 'Networking equipment', 'capital_asset', 8),
    ('M', 'Internet hardware', 'capital_asset', 9),
    ('M', 'Point-of-sale equipment', 'capital_asset', 10),
    ('M', 'CCTV equipment', 'capital_asset', 11),
    ('M', 'Security systems', 'capital_asset', 12),
    ('M', 'Technical support', null, 13),
    ('M', 'Software development', null, 14),
    ('M', 'IT maintenance', null, 15),
    ('M', 'Other technology costs', null, 16),
    -- N. Administration and Office Supplies
    ('N', 'Paper', null, 1),
    ('N', 'Printing', null, 2),
    ('N', 'Stationery', null, 3),
    ('N', 'Pens', null, 4),
    ('N', 'Registers', null, 5),
    ('N', 'Files', null, 6),
    ('N', 'Photocopying', null, 7),
    ('N', 'Office equipment', 'capital_asset', 8),
    ('N', 'Postage', null, 9),
    ('N', 'Documentation', null, 10),
    ('N', 'Administrative services', null, 11),
    ('N', 'Other office expenses', null, 12),
    -- O. Professional and Legal Services
    ('O', 'Accounting services', null, 1),
    ('O', 'Legal services', null, 2),
    ('O', 'Consultancy', null, 3),
    ('O', 'Audit fees', null, 4),
    ('O', 'Engineering consultancy', null, 5),
    ('O', 'Architectural consultancy', null, 6),
    ('O', 'Registration services', null, 7),
    ('O', 'Licensing services', null, 8),
    ('O', 'Other professional fees', null, 9),
    -- P. Licensing, Government Fees and Compliance
    ('P', 'Trade license', null, 1),
    ('P', 'Registration fees', null, 2),
    ('P', 'Permit fees', null, 3),
    ('P', 'Applicable taxes and fees', null, 4),
    ('P', 'Regulatory compliance', null, 5),
    ('P', 'Inspection fees', null, 6),
    ('P', 'Other official charges', null, 7),
    -- Q. Customer Experience and Hospitality
    ('Q', 'Guest welcome arrangements', null, 1),
    ('Q', 'Complimentary refreshments', null, 2),
    ('Q', 'Guest amenities', null, 3),
    ('Q', 'Customer service materials', null, 4),
    ('Q', 'Guest-related operational costs', null, 5),
    ('Q', 'Customer compensation', null, 6),
    ('Q', 'Approved service recovery costs', null, 7),
    ('Q', 'Other hospitality expenses', null, 8),
    -- R. Safety and Security
    ('R', 'Security services', null, 1),
    ('R', 'CCTV maintenance', null, 2),
    ('R', 'Fire extinguishers', null, 3),
    ('R', 'Fire safety equipment', 'capital_asset', 4),
    ('R', 'First aid supplies', null, 5),
    ('R', 'Emergency lighting', null, 6),
    ('R', 'Safety signage', null, 7),
    ('R', 'Protective equipment', null, 8),
    ('R', 'Other safety costs', null, 9),
    -- S. Events and Additional Services
    ('S', 'Event materials', null, 1),
    ('S', 'Event equipment', 'capital_asset', 2),
    ('S', 'Decoration', null, 3),
    ('S', 'Temporary staffing', null, 4),
    ('S', 'Event-specific purchases', null, 5),
    ('S', 'Guest activity supplies', null, 6),
    ('S', 'Other event-related costs', null, 7),
    -- T. Financial Costs (loan principal is never an expense; use Investments)
    ('T', 'Bank charges', null, 1),
    ('T', 'Payment processing fees', null, 2),
    ('T', 'Loan interest', null, 3),
    ('T', 'Other financing costs', null, 4),
    -- U. Insurance
    ('U', 'Property insurance', null, 1),
    ('U', 'Equipment insurance', null, 2),
    ('U', 'Liability insurance', null, 3),
    ('U', 'Vehicle insurance', null, 4),
    ('U', 'Other insurance premiums', null, 5),
    -- V. Assets and Capital Expenditure
    ('V', 'Buildings and qualifying improvements', null, 1),
    ('V', 'Furniture and fixtures', null, 2),
    ('V', 'Kitchen equipment', null, 3),
    ('V', 'Appliances', null, 4),
    ('V', 'Vehicles', null, 5),
    ('V', 'Computers and electronics', null, 6),
    ('V', 'Security equipment', null, 7),
    ('V', 'Long-term infrastructure', null, 8),
    ('V', 'Other capital assets', null, 9),
    -- W. Inventory and Procurement (periodic method: expensed on purchase)
    ('W', 'General supplies', null, 1),
    ('W', 'Restaurant inventory', null, 2),
    ('W', 'Housekeeping inventory', null, 3),
    ('W', 'Maintenance inventory', null, 4),
    ('W', 'Office supplies inventory', null, 5),
    ('W', 'Other stock purchases', null, 6),
    -- X. Refundable Deposits and Advances
    ('X', 'Rental security deposit', null, 1),
    ('X', 'Supplier advance', null, 2),
    ('X', 'Contractor advance', null, 3),
    ('X', 'Equipment deposit', null, 4),
    ('X', 'Other refundable advances', null, 5),
    -- Y. Pre-opening and Setup Costs
    ('Y', 'Initial supplies', null, 1),
    ('Y', 'Initial furniture', 'capital_asset', 2),
    ('Y', 'Setup services', null, 3),
    ('Y', 'Opening promotion', null, 4),
    ('Y', 'Staff recruitment and training', null, 5),
    ('Y', 'Initial operational materials', null, 6),
    ('Y', 'Other startup expenditure', null, 7)
)
insert into public.fin_categories (
  id, parent_id, code, name, classification, department_id,
  requires_approval, approval_threshold, requires_description, sort_order
)
select
  'cat-' || lower(s.code) || '-' || trim(both '-' from regexp_replace(lower(s.name), '[^a-z0-9]+', '-', 'g')),
  p.id,
  null,
  s.name,
  coalesce(s.classification, p.classification),
  p.department_id,
  p.requires_approval,
  p.approval_threshold,
  p.requires_description,
  s.sort_order
from subs s
join public.fin_categories p on p.id = 'cat-' || lower(s.code)
on conflict (id) do nothing;
